from pathlib import Path
p = Path('/tmp/sce-decision-dedup.py')
s = p.read_text()
old = r'''            documents.containsKey(skillPath)
            && documents.containsKey(templatePath)
            && documents.containsKey(syncPath)
            && documents[syncPath].contains("sole owner of decision qualification")
            && documents[syncPath].contains("System boundaries or ownership")
            && documents[syncPath].contains("Routine implementation details")
            && requiredDecisionOwnershipSkillTokens.every((token) -> documents[skillPath].contains(token))
            && forbiddenDecisionSkillGateTokens.every((token) -> !documents[skillPath].contains(token))
            && forbiddenDecisionSkillTemplateRestatementTokens.every((token) -> !documents[skillPath].contains(token))
            && documents[templatePath].contains("Status: {validated decision status}")
            && requiredDecisionTemplateTokens.every((token) -> documents[templatePath].contains(token))
            && !documents[templatePath].contains("Proposed|Accepted|Rejected|Deprecated|Superseded")
            && forbiddenDecisionTemplateGateTokens.every((token) -> !documents[templatePath].contains(token))
'''
new = r'''            documents.containsKey(skillPath)
            && documents.containsKey(templatePath)
            && documents.containsKey(syncPath)
            && documents[syncPath].contains("sole owner of decision qualification")
            && documents[skillPath].contains("## Qualification handoff")
            && documents[skillPath].contains("Treat the caller's gate result as authoritative")
            && documents[skillPath].contains("sole authority for\nthe persisted ADR schema and section semantics")
            && !documents[skillPath].contains("## Decision gate")
            && !documents[skillPath].contains("**Context** states")
            && !documents[skillPath].contains("**Decision** states")
            && documents[templatePath].contains("Status: {validated decision status}")
            && !documents[templatePath].contains("Proposed|Accepted|Rejected|Deprecated|Superseded")
'''
if s.count(old) != 1:
    raise SystemExit(f'expected one decision ownership condition block, found {s.count(old)}')
p.write_text(s.replace(old, new))
