//! Repository-scoped Agent Trace database adapter.
//!
//! One logical Git repository maps to one database at
//! `<state-root>/sce/repos/<repository-id>/agent-trace.db`. The schema
//! baseline is one fresh schema SQL file (`agent-trace-repository`
//! migrations), because repository-scoped databases are always created new;
//! there is no incremental chain and no migration path from legacy
//! checkout-scoped databases. Trace tables carry no `checkout_id` columns.
//!
//! `repository_metadata` additionally carries `source_instance_id`, a
//! physical-database identity independent of the logical `repository_id`
//! (added by the additive `002_repository_source_instance_id` migration and
//! generated by application code, never SQL).

use std::path::PathBuf;

use anyhow::Result;
use uuid::Uuid;

use crate::{
    generated_migrations,
    services::db::{DbSpec, TursoDb},
};

use super::{
    insert_agent_trace_with, insert_conversation_text_event_with, insert_diff_trace_with,
    insert_message_with, insert_messages_with, insert_part_with, insert_parts_with,
    insert_post_commit_patch_intersection_with, recent_diff_trace_patches_with,
    upsert_claude_model_state_with, AgentTraceInsert, ClaudeModelStateObservation, DiffTraceInsert,
    InsertMessageInsert, InsertPartInsert, PostCommitPatchIntersectionInsert,
    RecentDiffTracePatches,
};

const REPOSITORY_AGENT_TRACE_SCHEMA_SETUP_GUIDANCE: &str = "Run 'sce setup'.";

const SELECT_REPOSITORY_METADATA_SQL: &str =
    "SELECT repository_id, source_instance_id FROM repository_metadata WHERE id = 1";
const SELECT_SQLITE_OBJECT_SQL: &str =
    "SELECT name FROM sqlite_master WHERE type = ?1 AND name = ?2 LIMIT 1";
const RECORD_REPOSITORY_SCHEMA_MIGRATION_SQL: &str =
    "INSERT OR IGNORE INTO __sce_migrations (id) VALUES ('001_repository_schema')";
const REQUIRED_REPOSITORY_SCHEMA_TABLES: &[&str] = &[
    "repository_metadata",
    "diff_traces",
    "post_commit_patch_intersections",
    "agent_traces",
    "messages",
    "parts",
];

/// Seeds the single metadata row on first initialization; concurrent first
/// opens race safely because the conflicting insert is ignored and the stored
/// value is validated afterwards.
const INSERT_REPOSITORY_METADATA_SQL: &str =
    "INSERT INTO repository_metadata (id, repository_id) VALUES (1, ?1)
ON CONFLICT (id) DO NOTHING";

/// Atomically claims `source_instance_id` for the single metadata row: it
/// only ever replaces an empty placeholder, so a losing racer's candidate is
/// silently discarded (the `UPDATE` affects zero rows) and an already-valid
/// stored value is never overwritten.
const CLAIM_SOURCE_INSTANCE_ID_SQL: &str =
    "UPDATE repository_metadata SET source_instance_id = ?1 WHERE id = 1 AND source_instance_id = ''";

/// Physical database identity for one repository-scoped Agent Trace DB,
/// alongside the existing logical repository identity.
///
/// `repository_id` identifies the logical Git repository this database is
/// scoped to. `source_instance_id` identifies this one physical database
/// file's lineage: it is generated once per physical database, independent
/// of `repository_id`, remote URL, checkout ID, filesystem path, hostname, or
/// user/workspace identity, and stays stable across reopen and repeated
/// `sce setup` runs.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RepositoryMetadata {
    pub repository_id: String,
    pub source_instance_id: String,
}

/// Generate a new candidate source-instance identity.
///
/// Callers must not assume the result is UUID-shaped; `is_valid_source_instance_id`
/// only requires a non-empty (once trimmed) value.
pub fn generate_source_instance_id() -> String {
    Uuid::new_v4().to_string()
}

/// Whether a stored or candidate value is a usable source-instance identity.
pub fn is_valid_source_instance_id(value: &str) -> bool {
    !value.trim().is_empty()
}

/// Repository-scoped Agent Trace database configuration.
pub struct RepositoryAgentTraceDbSpec;

impl DbSpec for RepositoryAgentTraceDbSpec {
    fn db_name() -> &'static str {
        "repository Agent Trace DB"
    }

    fn db_path() -> Result<PathBuf> {
        anyhow::bail!(
            "repository Agent Trace DBs have no canonical spec path; resolve the \
             repository-scoped path and use the explicit-path constructors"
        )
    }

    fn migrations() -> &'static [(&'static str, &'static str)] {
        generated_migrations::AGENT_TRACE_REPOSITORY_MIGRATIONS
    }

    fn db_config_key() -> &'static str {
        "agent_trace_db"
    }
}

/// Repository-scoped Agent Trace Turso database adapter.
pub type RepositoryAgentTraceDb = TursoDb<RepositoryAgentTraceDbSpec>;

impl RepositoryAgentTraceDb {
    /// Open a repository-scoped Agent Trace database at an explicit path without
    /// running migrations, for read-only hook/runtime paths that must not
    /// migrate from a high-frequency caller.
    pub fn open_for_hooks_without_migrations_at(path: impl AsRef<std::path::Path>) -> Result<Self> {
        TursoDb::<RepositoryAgentTraceDbSpec>::open_without_migrations_at(path)
    }

    /// Verify that the repository-scoped schema baseline already exists.
    pub fn ensure_schema_ready_for_hooks(&self) -> Result<()> {
        self.ensure_schema_ready(REPOSITORY_AGENT_TRACE_SCHEMA_SETUP_GUIDANCE)
    }

    /// Repair the narrow concurrent-initialization case where the one-file
    /// schema batch completed but recording `__sce_migrations` raced with
    /// another first opener. This never creates trace tables; it only records
    /// the baseline migration after all required repository tables already
    /// exist.
    pub fn repair_missing_repository_schema_migration_metadata(&self) -> Result<()> {
        for table in REQUIRED_REPOSITORY_SCHEMA_TABLES {
            if !self.sqlite_object_exists("table", table)? {
                anyhow::bail!(
                    "repository Agent Trace DB schema is incomplete; missing table {table}. \
                     {REPOSITORY_AGENT_TRACE_SCHEMA_SETUP_GUIDANCE}"
                );
            }
        }

        self.execute(RECORD_REPOSITORY_SCHEMA_MIGRATION_SQL, ())?;
        self.ensure_schema_ready_for_hooks()
    }

    fn sqlite_object_exists(&self, object_type: &str, name: &str) -> Result<bool> {
        let rows = self.query_map(SELECT_SQLITE_OBJECT_SQL, (object_type, name), |row| {
            row.get::<String>(0).map_err(Into::into)
        })?;
        Ok(!rows.is_empty())
    }

    /// Seed repository metadata on first initialization, atomically claim a
    /// `source_instance_id` for this physical database if none is set yet,
    /// and validate the result on every open.
    ///
    /// The stored `repository_id` must match the resolved repository ID for
    /// this database path; a mismatch means the file does not belong to the
    /// resolved repository and is an error rather than a write target.
    /// `source_instance_id` is claimed with a concurrency-safe `UPDATE ...
    /// WHERE source_instance_id = ''`: concurrent first opens generate their
    /// own candidate, but only one claim can affect the row, so every caller
    /// re-reads the row afterward and returns whichever value actually won.
    pub fn verify_or_initialize_repository_metadata(
        &self,
        repository_id: &str,
    ) -> Result<RepositoryMetadata> {
        self.execute(INSERT_REPOSITORY_METADATA_SQL, (repository_id,))?;

        let Some((stored_repository_id, source_instance_id)) =
            self.select_repository_metadata_row()?
        else {
            anyhow::bail!(
                "repository Agent Trace DB metadata is missing its repository ID row. \
                 {REPOSITORY_AGENT_TRACE_SCHEMA_SETUP_GUIDANCE}"
            );
        };

        if stored_repository_id != repository_id {
            anyhow::bail!(
                "repository Agent Trace DB metadata mismatch: stored repository ID \
                 {stored_repository_id} does not match resolved repository ID {repository_id}"
            );
        }

        if is_valid_source_instance_id(&source_instance_id) {
            return Ok(RepositoryMetadata {
                repository_id: stored_repository_id,
                source_instance_id,
            });
        }

        let candidate = generate_source_instance_id();
        self.execute(CLAIM_SOURCE_INSTANCE_ID_SQL, (candidate.as_str(),))?;

        let (final_repository_id, final_source_instance_id) =
            self.select_repository_metadata_row()?.ok_or_else(|| {
                anyhow::anyhow!(
                    "repository Agent Trace DB metadata row disappeared after \
                     source-instance-id claim"
                )
            })?;

        if !is_valid_source_instance_id(&final_source_instance_id) {
            anyhow::bail!("repository Agent Trace DB failed to establish a source-instance ID");
        }

        Ok(RepositoryMetadata {
            repository_id: final_repository_id,
            source_instance_id: final_source_instance_id,
        })
    }

    fn select_repository_metadata_row(&self) -> Result<Option<(String, String)>> {
        let rows = self.query_map(SELECT_REPOSITORY_METADATA_SQL, (), |row| {
            Ok((row.get::<String>(0)?, row.get::<String>(1)?))
        })?;
        Ok(rows.into_iter().next())
    }

    /// Insert a diff trace payload into the repository-scoped `diff_traces`
    /// table. Rows remain repository-level; no checkout provenance is stored.
    pub fn insert_diff_trace(&self, input: DiffTraceInsert<'_>) -> Result<u64> {
        insert_diff_trace_with(self, input)
    }

    /// Insert a post-commit patch intersection into the repository-scoped
    /// `post_commit_patch_intersections` table.
    pub fn insert_post_commit_patch_intersection(
        &self,
        input: PostCommitPatchIntersectionInsert<'_>,
    ) -> Result<u64> {
        insert_post_commit_patch_intersection_with(self, input)
    }

    /// Insert a built Agent Trace payload into the repository-scoped
    /// `agent_traces` table.
    pub fn insert_agent_trace(&self, input: AgentTraceInsert<'_>) -> Result<u64> {
        insert_agent_trace_with(self, input)
    }

    pub fn upsert_claude_model_state(&self, input: ClaudeModelStateObservation) -> Result<u64> {
        upsert_claude_model_state_with(self, input)
    }

    pub fn claude_model_state_by_session_and_agent(
        &self,
        session_id: &str,
        agent_id: &str,
    ) -> Result<Option<ClaudeModelStateObservation>> {
        super::claude_model_state_by_session_and_agent_with(self, session_id, agent_id)
    }

    /// Query and parse recent diff trace patches within the inclusive time
    /// window for this repository-scoped database. Rows remain repository-level;
    /// no checkout filter or checkout provenance is applied.
    pub fn recent_diff_trace_patches(
        &self,
        cutoff_time_ms: i64,
        end_time_ms: i64,
    ) -> Result<RecentDiffTracePatches> {
        recent_diff_trace_patches_with(self, cutoff_time_ms, end_time_ms)
    }

    /// Insert a message row, ignoring duplicate `(session_id, message_id)`
    /// rows.
    #[allow(dead_code)]
    pub fn insert_message(&self, input: InsertMessageInsert) -> Result<u64> {
        insert_message_with(self, input)
    }

    /// Insert message rows with one multi-row statement, ignoring duplicate
    /// `(session_id, message_id)` rows.
    pub fn insert_messages(&self, inputs: Vec<InsertMessageInsert>) -> Result<u64> {
        insert_messages_with(self, inputs)
    }

    /// Append a part row (no upsert; multiple rows per message allowed).
    #[allow(dead_code)]
    pub fn insert_part(&self, input: InsertPartInsert) -> Result<u64> {
        insert_part_with(self, input)
    }

    /// Append part rows with one multi-row statement.
    pub fn insert_parts(&self, inputs: Vec<InsertPartInsert>) -> Result<u64> {
        insert_parts_with(self, inputs)
    }

    /// Atomically insert one conversation `messages` row and its one
    /// `parts` row: if `(message.session_id, message.message_id)` already
    /// exists, this is a no-op (`Ok(false)`); otherwise both rows insert
    /// together in one transaction (`Ok(true)`). Used by conversation
    /// text-event handlers (e.g. Codex `UserPromptSubmit`/`Stop`) in place
    /// of separate `insert_messages`/`insert_parts` calls, so a replayed or
    /// concurrent duplicate delivery never produces an orphaned `parts` row.
    pub fn insert_conversation_text_event(
        &self,
        message: InsertMessageInsert,
        part: InsertPartInsert,
    ) -> Result<bool> {
        insert_conversation_text_event_with(self, message, part, false)
    }

    /// Test-only counterpart of [`insert_conversation_text_event`] that
    /// forces the transaction to fail after the message insert and before
    /// the part insert, proving both statements roll back together.
    #[cfg(test)]
    pub(crate) fn insert_conversation_text_event_with_injected_failure(
        &self,
        message: InsertMessageInsert,
        part: InsertPartInsert,
    ) -> Result<bool> {
        insert_conversation_text_event_with(self, message, part, true)
    }
}

#[cfg(test)]
mod tests {
    use std::{
        fs,
        path::PathBuf,
        time::{SystemTime, UNIX_EPOCH},
    };

    use super::*;
    use crate::services::agent_trace_db::{
        MessageRole, ObservationKind, PartType, PAYLOAD_TYPE_PATCH,
    };

    fn valid_patch(path: &str, content: &str) -> String {
        format!(
            "Index: {path}\n===================================================================\n--- {path}\n+++ {path}\n@@ -0,0 +1,1 @@\n+{content}\n"
        )
    }

    fn unique_test_db_path(label: &str) -> PathBuf {
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time should be after Unix epoch")
            .as_nanos();
        std::env::temp_dir()
            .join(format!(
                "sce-repo-agent-trace-db-{label}-{}-{nonce}",
                std::process::id()
            ))
            .join("agent-trace.db")
    }

    fn remove_test_db(db_path: &std::path::Path) {
        if let Some(parent) = db_path.parent() {
            fs::remove_dir_all(parent).expect("test DB directory should be removed");
        }
    }

    fn sqlite_object_exists(db: &RepositoryAgentTraceDb, object_type: &str, name: &str) -> bool {
        let rows = db
            .query_map(
                "SELECT name FROM sqlite_master WHERE type = ?1 AND name = ?2",
                (object_type, name),
                |row| row.get::<String>(0).map_err(Into::into),
            )
            .expect("sqlite_master query should succeed");
        !rows.is_empty()
    }

    fn row_count(db: &RepositoryAgentTraceDb, table: &str) -> i64 {
        db.query_map(&format!("SELECT COUNT(*) FROM {table}"), (), |row| {
            row.get::<i64>(0).map_err(Into::into)
        })
        .expect("count query should succeed")
        .into_iter()
        .next()
        .expect("count row should exist")
    }

    fn table_sql(db: &RepositoryAgentTraceDb, name: &str) -> String {
        db.query_map(
            "SELECT sql FROM sqlite_master WHERE type = 'table' AND name = ?1",
            (name,),
            |row| row.get::<String>(0).map_err(Into::into),
        )
        .expect("sqlite_master sql query should succeed")
        .into_iter()
        .next()
        .unwrap_or_else(|| panic!("table '{name}' should exist"))
    }

    fn claude_observation(
        model_id: &str,
        observation_kind: ObservationKind,
        source: &str,
        observed_at_ms: i64,
    ) -> ClaudeModelStateObservation {
        ClaudeModelStateObservation {
            session_id: String::from("cc_session-1"),
            agent_id: String::new(),
            model_id: String::from(model_id),
            observation_kind,
            source: String::from(source),
            observed_at_ms,
        }
    }

    #[test]
    fn open_at_initializes_the_full_schema_from_one_migration() {
        let db_path = unique_test_db_path("baseline");
        let db = RepositoryAgentTraceDb::new_at(&db_path).expect("repository DB should open");

        for table in [
            "repository_metadata",
            "diff_traces",
            "post_commit_patch_intersections",
            "agent_traces",
            "messages",
            "parts",
            "claude_model_state",
        ] {
            assert!(
                sqlite_object_exists(&db, "table", table),
                "table '{table}' should exist"
            );
        }
        for index in [
            "idx_diff_traces_time_ms_id",
            "idx_agent_traces_agent_trace_id",
            "idx_agent_traces_remote_url",
            "idx_messages_session_message",
            "idx_messages_session_order",
            "idx_parts_session_message_order",
        ] {
            assert!(
                sqlite_object_exists(&db, "index", index),
                "index '{index}' should exist"
            );
        }
        for trigger in ["trg_messages_updated_at", "trg_parts_updated_at"] {
            assert!(
                sqlite_object_exists(&db, "trigger", trigger),
                "trigger '{trigger}' should exist"
            );
        }

        let applied_ids = db
            .query_map(
                "SELECT id FROM __sce_migrations ORDER BY id ASC",
                (),
                |row| row.get::<String>(0).map_err(Into::into),
            )
            .expect("migration metadata query should succeed");
        assert_eq!(
            applied_ids,
            vec![
                String::from("001_repository_schema"),
                String::from("002_repository_source_instance_id"),
                String::from("003_claude_model_state"),
            ],
            "repository DBs should be initialized from the baseline schema plus \
             its additive source-instance-id and Claude model-state migrations"
        );

        db.ensure_schema_ready_for_hooks()
            .expect("fresh repository DB schema should be ready");

        remove_test_db(&db_path);
    }

    #[test]
    fn pre_claude_model_state_database_is_upgraded_by_the_additive_migration() {
        let db_path = unique_test_db_path("claude-model-state-upgrade");
        let db = RepositoryAgentTraceDb::new_at(&db_path).expect("repository DB should open");
        db.execute("DROP TABLE claude_model_state", ())
            .expect("test should remove the post-003 table");
        db.execute(
            "DELETE FROM __sce_migrations WHERE id = '003_claude_model_state'",
            (),
        )
        .expect("test should remove the post-003 migration record");
        drop(db);

        let upgraded =
            RepositoryAgentTraceDb::new_at(&db_path).expect("pre-003 database should upgrade");
        assert!(sqlite_object_exists(
            &upgraded,
            "table",
            "claude_model_state"
        ));
        let applied_ids = upgraded
            .query_map(
                "SELECT id FROM __sce_migrations ORDER BY id ASC",
                (),
                |row| row.get::<String>(0).map_err(Into::into),
            )
            .expect("migration metadata query should succeed");
        assert_eq!(
            applied_ids,
            vec![
                String::from("001_repository_schema"),
                String::from("002_repository_source_instance_id"),
                String::from("003_claude_model_state"),
            ]
        );

        remove_test_db(&db_path);
    }

    #[test]
    fn claude_model_state_has_exact_scope_and_guarded_deterministic_updates() {
        let db_path = unique_test_db_path("claude-model-state");
        let db = RepositoryAgentTraceDb::new_at(&db_path).expect("repository DB should open");

        let initial = claude_observation("claude/A", ObservationKind::SessionStart, "startup", 100);
        assert_eq!(
            db.upsert_claude_model_state(initial.clone())
                .expect("initial write"),
            1
        );
        assert_eq!(
            db.claude_model_state_by_session_and_agent("cc_session-1", "")
                .expect("state lookup")
                .expect("state should exist"),
            initial
        );
        assert!(db
            .claude_model_state_by_session_and_agent("cc_session-1", "subagent")
            .expect("subagent lookup")
            .is_none());
        assert!(db
            .claude_model_state_by_session_and_agent("cc_other", "")
            .expect("other session lookup")
            .is_none());

        assert_eq!(
            db.upsert_claude_model_state(claude_observation(
                "claude/older",
                ObservationKind::PostModelSwitch,
                "picker",
                99,
            ))
            .expect("older write should be guarded"),
            0
        );
        assert_eq!(
            db.claude_model_state_by_session_and_agent("cc_session-1", "")
                .expect("state lookup")
                .expect("state should remain")
                .model_id,
            "claude/A"
        );

        let switched =
            claude_observation("claude/B", ObservationKind::PostModelSwitch, "picker", 101);
        assert_eq!(
            db.upsert_claude_model_state(switched.clone())
                .expect("newer write"),
            1
        );
        assert_eq!(
            db.upsert_claude_model_state(switched.clone())
                .expect("identical replay should be harmless"),
            0
        );

        assert_eq!(
            db.upsert_claude_model_state(claude_observation(
                "claude/C",
                ObservationKind::SessionStart,
                "resume",
                101,
            ))
            .expect("equal-time lower-priority write should be guarded"),
            0
        );
        assert_eq!(
            db.claude_model_state_by_session_and_agent("cc_session-1", "")
                .expect("state lookup")
                .expect("state should remain")
                .model_id,
            "claude/B"
        );

        remove_test_db(&db_path);
    }

    #[test]
    fn equal_time_same_kind_observations_use_a_stable_tie_break_and_concurrent_writes_converge() {
        let db_path = unique_test_db_path("claude-model-state-concurrent");
        let db = RepositoryAgentTraceDb::new_at(&db_path).expect("repository DB should open");
        drop(db);

        let db_path = std::sync::Arc::new(db_path);
        let handles: Vec<_> = (0..8)
            .map(|index| {
                let db_path = std::sync::Arc::clone(&db_path);
                std::thread::spawn(move || {
                    let db = RepositoryAgentTraceDb::open_without_migrations_at(&*db_path)
                        .expect("repository DB should reopen for concurrent state write");
                    db.upsert_claude_model_state(claude_observation(
                        &format!("claude/model-{index}"),
                        ObservationKind::PostModelSwitch,
                        "picker",
                        500,
                    ))
                    .expect("concurrent state write should succeed")
                })
            })
            .collect();
        for handle in handles {
            handle.join().expect("state writer should not panic");
        }

        let db = RepositoryAgentTraceDb::open_without_migrations_at(&*db_path)
            .expect("repository DB should reopen for verification");
        let state = db
            .claude_model_state_by_session_and_agent("cc_session-1", "")
            .expect("state lookup")
            .expect("concurrent writes should leave one state row");
        assert_eq!(state.model_id, "claude/model-7");
        assert_eq!(state.observation_kind, ObservationKind::PostModelSwitch);
        assert_eq!(state.observed_at_ms, 500);

        remove_test_db(&db_path);
    }

    #[test]
    fn trace_tables_have_no_checkout_id_columns() {
        let db_path = unique_test_db_path("no-checkout-id");
        let db = RepositoryAgentTraceDb::new_at(&db_path).expect("repository DB should open");

        for table in [
            "diff_traces",
            "post_commit_patch_intersections",
            "agent_traces",
            "messages",
            "parts",
        ] {
            let sql = table_sql(&db, table);
            assert!(
                !sql.contains("checkout_id"),
                "table '{table}' must not have a checkout_id column: {sql}"
            );
        }

        remove_test_db(&db_path);
    }

    #[test]
    fn repository_metadata_is_seeded_once_and_validated_on_reopen() {
        let db_path = unique_test_db_path("metadata");
        let repository_id = "a".repeat(64);

        let db = RepositoryAgentTraceDb::new_at(&db_path).expect("repository DB should open");
        let first = db
            .verify_or_initialize_repository_metadata(&repository_id)
            .expect("first metadata initialization should succeed");
        assert_eq!(first.repository_id, repository_id);
        assert!(
            is_valid_source_instance_id(&first.source_instance_id),
            "freshly initialized metadata should have a non-empty source-instance ID"
        );

        let repeated = db
            .verify_or_initialize_repository_metadata(&repository_id)
            .expect("repeated validation with the same repository ID should succeed");
        assert_eq!(
            repeated.source_instance_id, first.source_instance_id,
            "repeated initialization must not regenerate the source-instance ID"
        );
        drop(db);

        let reopened = RepositoryAgentTraceDb::open_without_migrations_at(&db_path)
            .expect("repository DB should reopen");
        let reopened_metadata = reopened
            .verify_or_initialize_repository_metadata(&repository_id)
            .expect("reopen validation with the matching repository ID should succeed");
        assert_eq!(
            reopened_metadata.source_instance_id, first.source_instance_id,
            "source-instance ID must be stable across reopen"
        );

        remove_test_db(&db_path);
    }

    #[test]
    fn source_instance_id_is_not_derived_from_repository_id_and_diverges_across_independent_dbs() {
        let first_db_path = unique_test_db_path("source-instance-first");
        let second_db_path = unique_test_db_path("source-instance-second");
        let repository_id = "a".repeat(64);

        let first_db = RepositoryAgentTraceDb::new_at(&first_db_path)
            .expect("first repository DB should open");
        let second_db = RepositoryAgentTraceDb::new_at(&second_db_path)
            .expect("second repository DB should open");

        let first_metadata = first_db
            .verify_or_initialize_repository_metadata(&repository_id)
            .expect("first DB metadata initialization should succeed");
        let second_metadata = second_db
            .verify_or_initialize_repository_metadata(&repository_id)
            .expect("second DB metadata initialization should succeed");

        assert_eq!(first_metadata.repository_id, second_metadata.repository_id);
        assert_ne!(
            first_metadata.source_instance_id, second_metadata.source_instance_id,
            "two independently created databases for the same logical repository \
             must diverge in source-instance ID"
        );
        assert_ne!(
            first_metadata.source_instance_id, repository_id,
            "source-instance ID must not be derived from repository_id"
        );

        remove_test_db(&first_db_path);
        remove_test_db(&second_db_path);
    }

    #[test]
    fn concurrent_initialization_converges_on_one_source_instance_id() {
        use std::sync::Arc;

        let db_path = unique_test_db_path("concurrent-source-instance");
        let repository_id = "a".repeat(64);

        // Create the schema up front so both threads race only on the
        // metadata claim, not schema creation.
        RepositoryAgentTraceDb::new_at(&db_path).expect("repository DB should open");

        let db_path = Arc::new(db_path);
        let handles: Vec<_> = (0..4)
            .map(|_| {
                let db_path = Arc::clone(&db_path);
                let repository_id = repository_id.clone();
                std::thread::spawn(move || {
                    let db = RepositoryAgentTraceDb::open_without_migrations_at(&*db_path)
                        .expect("repository DB should reopen for concurrent claim");
                    db.verify_or_initialize_repository_metadata(&repository_id)
                        .expect("concurrent metadata initialization should succeed")
                })
            })
            .collect();

        let results: Vec<RepositoryMetadata> = handles
            .into_iter()
            .map(|handle| handle.join().expect("worker thread should not panic"))
            .collect();

        let winning_id = results[0].source_instance_id.clone();
        for result in &results {
            assert_eq!(
                result.source_instance_id, winning_id,
                "all concurrent initializations must converge on one persisted \
                 source-instance ID"
            );
        }

        remove_test_db(&db_path);
    }

    #[test]
    fn mismatched_repository_metadata_errors_on_open() {
        let db_path = unique_test_db_path("mismatch");
        let stored_repository_id = "a".repeat(64);
        let other_repository_id = "b".repeat(64);

        let db = RepositoryAgentTraceDb::new_at(&db_path).expect("repository DB should open");
        let stored = db
            .verify_or_initialize_repository_metadata(&stored_repository_id)
            .expect("first metadata initialization should succeed");

        let error = db
            .verify_or_initialize_repository_metadata(&other_repository_id)
            .expect_err("mismatched repository ID should fail validation");
        let message = error.to_string();
        assert!(
            message.contains("metadata mismatch"),
            "unexpected error: {message}"
        );
        assert!(message.contains(&stored_repository_id));
        assert!(message.contains(&other_repository_id));

        let unchanged = db
            .verify_or_initialize_repository_metadata(&stored_repository_id)
            .expect("re-validating with the original repository ID should still succeed");
        assert_eq!(
            unchanged.source_instance_id, stored.source_instance_id,
            "a rejected mismatched claim must not alter the stored source-instance ID"
        );

        remove_test_db(&db_path);
    }

    #[test]
    fn baseline_only_fixture_migrates_and_gets_a_stable_source_instance_id() {
        let db_path = unique_test_db_path("baseline-only-fixture");
        let repository_id = "a".repeat(64);

        // Simulate a database created before migration 002 existed: build the
        // pre-002 `repository_metadata` shape (no `source_instance_id`
        // column) and record only migration 001 as applied, so opening with
        // the current embedded migration set exercises the real 001-applied,
        // 002-pending upgrade path.
        let baseline_only = RepositoryAgentTraceDb::open_without_migrations_at(&db_path)
            .expect("baseline-only repository DB should open");
        baseline_only
            .execute(
                "CREATE TABLE IF NOT EXISTS __sce_migrations (
    id TEXT PRIMARY KEY,
    applied_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
)",
                (),
            )
            .expect("migration metadata table should create");
        baseline_only
            .execute(
                "CREATE TABLE IF NOT EXISTS repository_metadata (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    repository_id TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
)",
                (),
            )
            .expect("baseline repository_metadata table should create");
        baseline_only
            .execute(
                "INSERT INTO __sce_migrations (id) VALUES ('001_repository_schema')",
                (),
            )
            .expect("baseline migration record should insert");
        baseline_only
            .execute(
                "INSERT INTO repository_metadata (id, repository_id) VALUES (1, ?1)",
                (repository_id.as_str(),),
            )
            .expect("baseline metadata row should seed");
        drop(baseline_only);

        let migrated =
            RepositoryAgentTraceDb::new_at(&db_path).expect("repository DB should migrate to 002");
        let metadata = migrated
            .verify_or_initialize_repository_metadata(&repository_id)
            .expect("metadata initialization after migrating from baseline should succeed");
        assert_eq!(metadata.repository_id, repository_id);
        assert!(
            is_valid_source_instance_id(&metadata.source_instance_id),
            "migrating from a baseline-only fixture should populate a valid source-instance ID"
        );
        drop(migrated);

        let reopened = RepositoryAgentTraceDb::open_without_migrations_at(&db_path)
            .expect("migrated repository DB should reopen");
        let reopened_metadata = reopened
            .verify_or_initialize_repository_metadata(&repository_id)
            .expect("reopen after migration should succeed");
        assert_eq!(
            reopened_metadata.source_instance_id, metadata.source_instance_id,
            "source-instance ID populated during migration must remain stable across reopen"
        );

        remove_test_db(&db_path);
    }

    #[test]
    fn repository_scoped_write_methods_insert_all_agent_trace_rows() {
        let db_path = unique_test_db_path("writes");
        let db = RepositoryAgentTraceDb::new_at(&db_path).expect("repository DB should open");

        db.insert_diff_trace(DiffTraceInsert {
            time_ms: 1_000,
            session_id: "oc_session-1",
            patch: "Index: notes.md\n===================================================================\n--- notes.md\n+++ notes.md\n@@ -0,0 +1,1 @@\n+hello\n",
            model_id: Some("provider/model"),
            tool_name: "opencode",
            tool_version: Some("1.2.3"),
            payload_type: PAYLOAD_TYPE_PATCH,
        })
        .expect("diff trace insert should succeed");

        db.insert_post_commit_patch_intersection(PostCommitPatchIntersectionInsert {
            commit_id: "abc123",
            post_commit_time_ms: 2_000,
            recent_window_cutoff_ms: 1_000,
            recent_window_end_ms: 2_000,
            loaded_diff_trace_count: 1,
            skipped_diff_trace_count: 0,
            intersection_patch: "Index: notes.md\n===================================================================\n--- notes.md\n+++ notes.md\n@@ -0,0 +1,1 @@\n+hello\n",
        })
        .expect("post-commit intersection insert should succeed");

        db.insert_agent_trace(AgentTraceInsert {
            commit_id: "abc123",
            commit_time_ms: 2_000,
            trace_json: r#"{"id":"trace-1"}"#,
            agent_trace_id: "trace-1",
            url: "https://sce.crocoder.dev/agent-trace/trace-1",
            remote_url: "https://github.com/acme/widgets",
        })
        .expect("agent trace insert should succeed");

        db.insert_message(InsertMessageInsert {
            session_id: "oc_session-1".to_string(),
            message_id: "message-1".to_string(),
            role: MessageRole::Assistant,
            generated_at_unix_ms: 1_000,
        })
        .expect("message insert should succeed");
        db.insert_messages(vec![InsertMessageInsert {
            session_id: "oc_session-1".to_string(),
            message_id: "message-2".to_string(),
            role: MessageRole::User,
            generated_at_unix_ms: 1_001,
        }])
        .expect("batch message insert should succeed");

        db.insert_part(InsertPartInsert {
            part_type: PartType::Text,
            text: "hello".to_string(),
            session_id: "oc_session-1".to_string(),
            message_id: "message-1".to_string(),
            generated_at_unix_ms: 1_000,
        })
        .expect("part insert should succeed");
        db.insert_parts(vec![InsertPartInsert {
            part_type: PartType::Patch,
            text: "patch text".to_string(),
            session_id: "oc_session-1".to_string(),
            message_id: "message-2".to_string(),
            generated_at_unix_ms: 1_001,
        }])
        .expect("batch part insert should succeed");

        for (table, expected_count) in [
            ("diff_traces", 1_i64),
            ("post_commit_patch_intersections", 1),
            ("agent_traces", 1),
            ("messages", 2),
            ("parts", 2),
        ] {
            let count = db
                .query_map(&format!("SELECT COUNT(*) FROM {table}"), (), |row| {
                    row.get::<i64>(0).map_err(Into::into)
                })
                .expect("count query should succeed")
                .into_iter()
                .next()
                .expect("count row should exist");
            assert_eq!(count, expected_count, "unexpected row count for {table}");
        }

        remove_test_db(&db_path);
    }

    fn conversation_text_event_fixture() -> (InsertMessageInsert, InsertPartInsert) {
        (
            InsertMessageInsert {
                session_id: "cx_session-1".to_string(),
                message_id: "cx:turn-1:user".to_string(),
                role: MessageRole::User,
                generated_at_unix_ms: 1_000,
            },
            InsertPartInsert {
                part_type: PartType::Text,
                text: "hello world".to_string(),
                session_id: "cx_session-1".to_string(),
                message_id: "cx:turn-1:user".to_string(),
                generated_at_unix_ms: 1_000,
            },
        )
    }

    #[test]
    fn insert_conversation_text_event_inserts_message_and_part_together() {
        let db_path = unique_test_db_path("conversation-event-insert");
        let db = RepositoryAgentTraceDb::new_at(&db_path).expect("repository DB should open");
        let (message, part) = conversation_text_event_fixture();

        let inserted = db
            .insert_conversation_text_event(message, part)
            .expect("conversation text event insert should succeed");

        assert!(inserted, "first delivery should insert both rows");
        assert_eq!(row_count(&db, "messages"), 1);
        assert_eq!(row_count(&db, "parts"), 1);

        remove_test_db(&db_path);
    }

    #[test]
    fn insert_conversation_text_event_is_a_no_op_on_sequential_replay() {
        let db_path = unique_test_db_path("conversation-event-replay");
        let db = RepositoryAgentTraceDb::new_at(&db_path).expect("repository DB should open");

        let (message, part) = conversation_text_event_fixture();
        let first = db
            .insert_conversation_text_event(message, part)
            .expect("first delivery should succeed");

        let (message, part) = conversation_text_event_fixture();
        let second = db
            .insert_conversation_text_event(message, part)
            .expect("replayed delivery should succeed");

        assert!(first);
        assert!(!second, "a replayed delivery must be a no-op");
        assert_eq!(row_count(&db, "messages"), 1);
        assert_eq!(row_count(&db, "parts"), 1);

        remove_test_db(&db_path);
    }

    #[test]
    fn insert_conversation_text_event_ten_sequential_replays_still_leave_one_row_pair() {
        let db_path = unique_test_db_path("conversation-event-replay-ten");
        let db = RepositoryAgentTraceDb::new_at(&db_path).expect("repository DB should open");

        for _ in 0..10 {
            let (message, part) = conversation_text_event_fixture();
            db.insert_conversation_text_event(message, part)
                .expect("every replayed delivery should succeed");
        }

        assert_eq!(row_count(&db, "messages"), 1);
        assert_eq!(row_count(&db, "parts"), 1);

        remove_test_db(&db_path);
    }

    #[test]
    fn insert_conversation_text_event_injected_failure_rolls_back_both_rows() {
        let db_path = unique_test_db_path("conversation-event-rollback");
        let db = RepositoryAgentTraceDb::new_at(&db_path).expect("repository DB should open");
        let (message, part) = conversation_text_event_fixture();

        let error = db
            .insert_conversation_text_event_with_injected_failure(message, part)
            .expect_err("an injected failure before the part insert should propagate as an error");
        assert!(error.to_string().contains("injected failure"));

        assert_eq!(
            row_count(&db, "messages"),
            0,
            "the message row must roll back along with the failed part insert"
        );
        assert_eq!(row_count(&db, "parts"), 0);

        remove_test_db(&db_path);
    }

    #[test]
    fn insert_conversation_text_event_concurrent_duplicate_delivery_leaves_one_row_pair() {
        use std::sync::Arc;

        let db_path = unique_test_db_path("conversation-event-concurrent");

        // Create the schema up front so every thread races only on the
        // conversation text event insert, not schema creation, mirroring
        // `concurrent_initialization_converges_on_one_source_instance_id`.
        RepositoryAgentTraceDb::new_at(&db_path).expect("repository DB should open");

        let db_path = Arc::new(db_path);
        let handles: Vec<_> = (0..4)
            .map(|_| {
                let db_path = Arc::clone(&db_path);
                std::thread::spawn(move || {
                    let db = RepositoryAgentTraceDb::open_without_migrations_at(&*db_path)
                        .expect("repository DB should reopen for concurrent delivery");
                    let (message, part) = conversation_text_event_fixture();
                    db.insert_conversation_text_event(message, part)
                })
            })
            .collect();

        let results: Vec<bool> = handles
            .into_iter()
            .map(|handle| {
                handle
                    .join()
                    .expect("worker thread should not panic")
                    .expect("every concurrent delivery attempt should succeed")
            })
            .collect();

        assert_eq!(
            results.iter().filter(|inserted| **inserted).count(),
            1,
            "exactly one concurrent delivery should have performed the insert"
        );

        let db = RepositoryAgentTraceDb::open_without_migrations_at(&*db_path)
            .expect("repository DB should reopen for verification");
        assert_eq!(row_count(&db, "messages"), 1);
        assert_eq!(row_count(&db, "parts"), 1);

        remove_test_db(&db_path);
    }

    #[test]
    fn recent_diff_trace_reads_all_repository_rows_without_checkout_filter() {
        let db_path = unique_test_db_path("recent-repository-level");
        let db = RepositoryAgentTraceDb::new_at(&db_path).expect("repository DB should open");

        db.insert_diff_trace(DiffTraceInsert {
            time_ms: 999,
            session_id: "oc_before-cutoff",
            patch: &valid_patch("notes/before.md", "before"),
            model_id: Some("provider/model"),
            tool_name: "opencode",
            tool_version: Some("1.2.3"),
            payload_type: PAYLOAD_TYPE_PATCH,
        })
        .expect("before-cutoff diff trace insert should succeed");
        db.insert_diff_trace(DiffTraceInsert {
            time_ms: 1_000,
            session_id: "oc_checkout-a-session",
            patch: &valid_patch("notes/a.md", "same repository checkout a"),
            model_id: Some("provider/model-a"),
            tool_name: "opencode",
            tool_version: Some("1.2.3"),
            payload_type: PAYLOAD_TYPE_PATCH,
        })
        .expect("checkout-a diff trace insert should succeed");
        db.insert_diff_trace(DiffTraceInsert {
            time_ms: 1_500,
            session_id: "pi_checkout-b-session",
            patch: &valid_patch("notes/b.md", "same repository checkout b"),
            model_id: Some("provider/model-b"),
            tool_name: "pi",
            tool_version: None,
            payload_type: PAYLOAD_TYPE_PATCH,
        })
        .expect("checkout-b diff trace insert should succeed");
        db.insert_diff_trace(DiffTraceInsert {
            time_ms: 2_001,
            session_id: "oc_after-end",
            patch: &valid_patch("notes/after.md", "after"),
            model_id: Some("provider/model"),
            tool_name: "opencode",
            tool_version: Some("1.2.3"),
            payload_type: PAYLOAD_TYPE_PATCH,
        })
        .expect("after-end diff trace insert should succeed");

        let recent = db
            .recent_diff_trace_patches(1_000, 2_000)
            .expect("recent repository diff traces should load");

        assert_eq!(recent.loaded_count(), 2);
        assert_eq!(recent.skipped_count(), 0);
        assert_eq!(
            recent
                .patches
                .iter()
                .map(|patch| (
                    patch.time_ms,
                    patch.session_id.as_str(),
                    patch.tool_name.as_deref()
                ))
                .collect::<Vec<_>>(),
            vec![
                (1_000, "oc_checkout-a-session", Some("opencode")),
                (1_500, "pi_checkout-b-session", Some("pi")),
            ]
        );

        remove_test_db(&db_path);
    }

    #[test]
    fn recent_diff_trace_reads_are_isolated_by_repository_db_path() {
        let first_db_path = unique_test_db_path("recent-repo-one");
        let second_db_path = unique_test_db_path("recent-repo-two");
        let first_db = RepositoryAgentTraceDb::new_at(&first_db_path)
            .expect("first repository DB should open");
        let second_db = RepositoryAgentTraceDb::new_at(&second_db_path)
            .expect("second repository DB should open");

        first_db
            .insert_diff_trace(DiffTraceInsert {
                time_ms: 1_000,
                session_id: "oc_first-repo",
                patch: &valid_patch("notes/first.md", "first repository"),
                model_id: Some("provider/first"),
                tool_name: "opencode",
                tool_version: Some("1.2.3"),
                payload_type: PAYLOAD_TYPE_PATCH,
            })
            .expect("first repository diff trace insert should succeed");
        second_db
            .insert_diff_trace(DiffTraceInsert {
                time_ms: 1_000,
                session_id: "oc_second-repo",
                patch: &valid_patch("notes/second.md", "second repository"),
                model_id: Some("provider/second"),
                tool_name: "opencode",
                tool_version: Some("1.2.3"),
                payload_type: PAYLOAD_TYPE_PATCH,
            })
            .expect("second repository diff trace insert should succeed");

        let first_recent = first_db
            .recent_diff_trace_patches(0, 2_000)
            .expect("first repository recent traces should load");
        let second_recent = second_db
            .recent_diff_trace_patches(0, 2_000)
            .expect("second repository recent traces should load");

        assert_eq!(first_recent.loaded_count(), 1);
        assert_eq!(second_recent.loaded_count(), 1);
        assert_eq!(first_recent.patches[0].session_id, "oc_first-repo");
        assert_eq!(second_recent.patches[0].session_id, "oc_second-repo");
        assert_ne!(
            first_recent.patches[0].session_id,
            second_recent.patches[0].session_id
        );

        remove_test_db(&first_db_path);
        remove_test_db(&second_db_path);
    }

    #[test]
    fn spec_path_constructor_is_rejected() {
        let error = RepositoryAgentTraceDbSpec::db_path()
            .expect_err("repository DBs must not have a canonical spec path");
        assert!(error.to_string().contains("explicit-path"));
    }
}
