name: CLI integration tests

on:
  push:

permissions:
  contents: read

jobs:
  cli-integration-tests:
    name: Run cli integration tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    timeout-minutes: 25
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Run CLI integration test app
        run: nix run .#cli-integration-tests
